language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get -y install gcc-7 g++-7 libboost-test-dev doxygen
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target package
  - cd -
  - doxygen
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T build/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uasvgit:$BINTRAY_API_KEY "https://api.bintray.com/content/savaorg/otuscpp/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    - rm -rf build
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
